#ifndef _INCLUDED_AMPA_STD8_synapses_create_generator_codeobject_1
#define _INCLUDED_AMPA_STD8_synapses_create_generator_codeobject_1

void _run_AMPA_STD8_synapses_create_generator_codeobject_1();


#endif
