
#ifndef _BRIAN_OBJECTS_H
#define _BRIAN_OBJECTS_H

#include "synapses_classes.h"
#include "brianlib/clocks.h"
#include "brianlib/dynamic_array.h"
#include "brianlib/stdint_compat.h"
#include "network.h"
#include "randomkit.h"
#include<vector>


namespace brian {

// In OpenMP we need one state per thread
extern std::vector< rk_state* > _mersenne_twister_states;

//////////////// clocks ///////////////////
extern Clock defaultclock;

//////////////// networks /////////////////
extern Network network;

//////////////// dynamic arrays ///////////
extern std::vector<int32_t> _dynamic_array_AMPA0__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA0__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA0_delay;
extern std::vector<double> _dynamic_array_AMPA0_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA0_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA0_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA0_weight;
extern std::vector<int32_t> _dynamic_array_AMPA2__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA2__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA2_delay;
extern std::vector<double> _dynamic_array_AMPA2_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA2_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA2_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA2_weight;
extern std::vector<int32_t> _dynamic_array_AMPA3__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA3__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA3_delay;
extern std::vector<double> _dynamic_array_AMPA3_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA3_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA3_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA3_weight;
extern std::vector<int32_t> _dynamic_array_AMPA7__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA7__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA7_delay;
extern std::vector<double> _dynamic_array_AMPA7_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA7_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA7_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA7_weight;
extern std::vector<int32_t> _dynamic_array_AMPA_STD1__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA_STD1__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA_STD1_delay;
extern std::vector<double> _dynamic_array_AMPA_STD1_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA_STD1_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA_STD1_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA_STD1_weight;
extern std::vector<int32_t> _dynamic_array_AMPA_STD8__synaptic_post;
extern std::vector<int32_t> _dynamic_array_AMPA_STD8__synaptic_pre;
extern std::vector<double> _dynamic_array_AMPA_STD8_delay;
extern std::vector<double> _dynamic_array_AMPA_STD8_delay_1;
extern std::vector<int32_t> _dynamic_array_AMPA_STD8_N_incoming;
extern std::vector<int32_t> _dynamic_array_AMPA_STD8_N_outgoing;
extern std::vector<double> _dynamic_array_AMPA_STD8_weight;
extern std::vector<int32_t> _dynamic_array_GABA_B10__synaptic_post;
extern std::vector<int32_t> _dynamic_array_GABA_B10__synaptic_pre;
extern std::vector<double> _dynamic_array_GABA_B10_delay;
extern std::vector<double> _dynamic_array_GABA_B10_delay_1;
extern std::vector<int32_t> _dynamic_array_GABA_B10_N_incoming;
extern std::vector<int32_t> _dynamic_array_GABA_B10_N_outgoing;
extern std::vector<double> _dynamic_array_GABA_B10_weight;
extern std::vector<int32_t> _dynamic_array_GABA_B4__synaptic_post;
extern std::vector<int32_t> _dynamic_array_GABA_B4__synaptic_pre;
extern std::vector<double> _dynamic_array_GABA_B4_delay;
extern std::vector<double> _dynamic_array_GABA_B4_delay_1;
extern std::vector<int32_t> _dynamic_array_GABA_B4_N_incoming;
extern std::vector<int32_t> _dynamic_array_GABA_B4_N_outgoing;
extern std::vector<double> _dynamic_array_GABA_B4_weight;
extern std::vector<int32_t> _dynamic_array_GABA_B5__synaptic_post;
extern std::vector<int32_t> _dynamic_array_GABA_B5__synaptic_pre;
extern std::vector<double> _dynamic_array_GABA_B5_delay;
extern std::vector<double> _dynamic_array_GABA_B5_delay_1;
extern std::vector<int32_t> _dynamic_array_GABA_B5_N_incoming;
extern std::vector<int32_t> _dynamic_array_GABA_B5_N_outgoing;
extern std::vector<double> _dynamic_array_GABA_B5_weight;
extern std::vector<int32_t> _dynamic_array_GABA_B6__synaptic_post;
extern std::vector<int32_t> _dynamic_array_GABA_B6__synaptic_pre;
extern std::vector<double> _dynamic_array_GABA_B6_delay;
extern std::vector<double> _dynamic_array_GABA_B6_delay_1;
extern std::vector<int32_t> _dynamic_array_GABA_B6_N_incoming;
extern std::vector<int32_t> _dynamic_array_GABA_B6_N_outgoing;
extern std::vector<double> _dynamic_array_GABA_B6_weight;
extern std::vector<int32_t> _dynamic_array_GABA_B9__synaptic_post;
extern std::vector<int32_t> _dynamic_array_GABA_B9__synaptic_pre;
extern std::vector<double> _dynamic_array_GABA_B9_delay;
extern std::vector<double> _dynamic_array_GABA_B9_delay_1;
extern std::vector<int32_t> _dynamic_array_GABA_B9_N_incoming;
extern std::vector<int32_t> _dynamic_array_GABA_B9_N_outgoing;
extern std::vector<double> _dynamic_array_GABA_B9_weight;
extern std::vector<int32_t> _dynamic_array_mon_neuron_input_i;
extern std::vector<double> _dynamic_array_mon_neuron_input_t;
extern std::vector<int32_t> _dynamic_array_PC_output_i;
extern std::vector<double> _dynamic_array_PC_output_t;
extern std::vector<int32_t> _dynamic_array_PV_output_i;
extern std::vector<double> _dynamic_array_PV_output_t;
extern std::vector<int32_t> _dynamic_array_SpikeGenerator__timebins;
extern std::vector<int32_t> _dynamic_array_SpikeGenerator_neuron_index;
extern std::vector<int32_t> _dynamic_array_SpikeGenerator_spike_number;
extern std::vector<double> _dynamic_array_SpikeGenerator_spike_time;
extern std::vector<int32_t> _dynamic_array_SST_output_i;
extern std::vector<double> _dynamic_array_SST_output_t;
extern std::vector<double> _dynamic_array_statemonitor_10_t;
extern std::vector<double> _dynamic_array_statemonitor_11_t;
extern std::vector<double> _dynamic_array_statemonitor_12_t;
extern std::vector<double> _dynamic_array_statemonitor_13_t;
extern std::vector<double> _dynamic_array_statemonitor_1_t;
extern std::vector<double> _dynamic_array_statemonitor_2_t;
extern std::vector<double> _dynamic_array_statemonitor_3_t;
extern std::vector<double> _dynamic_array_statemonitor_4_t;
extern std::vector<double> _dynamic_array_statemonitor_5_t;
extern std::vector<double> _dynamic_array_statemonitor_6_t;
extern std::vector<double> _dynamic_array_statemonitor_7_t;
extern std::vector<double> _dynamic_array_statemonitor_8_t;
extern std::vector<double> _dynamic_array_statemonitor_9_t;
extern std::vector<double> _dynamic_array_statemonitor_t;

//////////////// arrays ///////////////////
extern int32_t *_array_AMPA0_N;
extern const int _num__array_AMPA0_N;
extern int32_t *_array_AMPA2_N;
extern const int _num__array_AMPA2_N;
extern int32_t *_array_AMPA3_N;
extern const int _num__array_AMPA3_N;
extern int32_t *_array_AMPA7_N;
extern const int _num__array_AMPA7_N;
extern int32_t *_array_AMPA_STD1_N;
extern const int _num__array_AMPA_STD1_N;
extern int32_t *_array_AMPA_STD8_N;
extern const int _num__array_AMPA_STD8_N;
extern int32_t *_array_Core_0__spikespace;
extern const int _num__array_Core_0__spikespace;
extern double *_array_Core_0_alpha_ahp;
extern const int _num__array_Core_0_alpha_ahp;
extern double *_array_Core_0_alpha_ampa;
extern const int _num__array_Core_0_alpha_ampa;
extern double *_array_Core_0_alpha_ampa_std;
extern const int _num__array_Core_0_alpha_ampa_std;
extern double *_array_Core_0_alpha_gaba_a;
extern const int _num__array_Core_0_alpha_gaba_a;
extern double *_array_Core_0_alpha_gaba_b;
extern const int _num__array_Core_0_alpha_gaba_b;
extern double *_array_Core_0_alpha_nmda;
extern const int _num__array_Core_0_alpha_nmda;
extern double *_array_Core_0_alpha_soma;
extern const int _num__array_Core_0_alpha_soma;
extern double *_array_Core_0_Campa;
extern const int _num__array_Core_0_Campa;
extern double *_array_Core_0_Campa_std;
extern const int _num__array_Core_0_Campa_std;
extern double *_array_Core_0_Cgaba_a;
extern const int _num__array_Core_0_Cgaba_a;
extern double *_array_Core_0_Cgaba_b;
extern const int _num__array_Core_0_Cgaba_b;
extern double *_array_Core_0_Cnmda;
extern const int _num__array_Core_0_Cnmda;
extern double *_array_Core_0_Csoma_ahp;
extern const int _num__array_Core_0_Csoma_ahp;
extern double *_array_Core_0_Csoma_mem;
extern const int _num__array_Core_0_Csoma_mem;
extern int32_t *_array_Core_0_i;
extern const int _num__array_Core_0_i;
extern double *_array_Core_0_I0;
extern const int _num__array_Core_0_I0;
extern double *_array_Core_0_Iampa;
extern const int _num__array_Core_0_Iampa;
extern double *_array_Core_0_Iampa_std;
extern const int _num__array_Core_0_Iampa_std;
extern double *_array_Core_0_Iampa_std_tau;
extern const int _num__array_Core_0_Iampa_std_tau;
extern double *_array_Core_0_Iampa_tau;
extern const int _num__array_Core_0_Iampa_tau;
extern double *_array_Core_0_Iampa_w0;
extern const int _num__array_Core_0_Iampa_w0;
extern double *_array_Core_0_Idischarge_w;
extern const int _num__array_Core_0_Idischarge_w;
extern double *_array_Core_0_Igaba_a;
extern const int _num__array_Core_0_Igaba_a;
extern double *_array_Core_0_Igaba_a_tau;
extern const int _num__array_Core_0_Igaba_a_tau;
extern double *_array_Core_0_Igaba_a_w0;
extern const int _num__array_Core_0_Igaba_a_w0;
extern double *_array_Core_0_Igaba_b;
extern const int _num__array_Core_0_Igaba_b;
extern double *_array_Core_0_Igaba_b_tau;
extern const int _num__array_Core_0_Igaba_b_tau;
extern double *_array_Core_0_Igaba_b_w0;
extern const int _num__array_Core_0_Igaba_b_w0;
extern double *_array_Core_0_Inmda;
extern const int _num__array_Core_0_Inmda;
extern double *_array_Core_0_Inmda_tau;
extern const int _num__array_Core_0_Inmda_tau;
extern double *_array_Core_0_Inmda_thr;
extern const int _num__array_Core_0_Inmda_thr;
extern double *_array_Core_0_Inmda_w0;
extern const int _num__array_Core_0_Inmda_w0;
extern double *_array_Core_0_Isoma_ahp;
extern const int _num__array_Core_0_Isoma_ahp;
extern double *_array_Core_0_Isoma_ahp_g;
extern const int _num__array_Core_0_Isoma_ahp_g;
extern double *_array_Core_0_Isoma_ahp_tau;
extern const int _num__array_Core_0_Isoma_ahp_tau;
extern double *_array_Core_0_Isoma_ahp_w;
extern const int _num__array_Core_0_Isoma_ahp_w;
extern double *_array_Core_0_Isoma_const;
extern const int _num__array_Core_0_Isoma_const;
extern double *_array_Core_0_Isoma_dpi_tau;
extern const int _num__array_Core_0_Isoma_dpi_tau;
extern double *_array_Core_0_Isoma_mem;
extern const int _num__array_Core_0_Isoma_mem;
extern double *_array_Core_0_Isoma_pfb_gain;
extern const int _num__array_Core_0_Isoma_pfb_gain;
extern double *_array_Core_0_Isoma_pfb_norm;
extern const int _num__array_Core_0_Isoma_pfb_norm;
extern double *_array_Core_0_Isoma_pfb_th;
extern const int _num__array_Core_0_Isoma_pfb_th;
extern double *_array_Core_0_Isoma_reset;
extern const int _num__array_Core_0_Isoma_reset;
extern double *_array_Core_0_Isoma_th;
extern const int _num__array_Core_0_Isoma_th;
extern double *_array_Core_0_kn;
extern const int _num__array_Core_0_kn;
extern double *_array_Core_0_kp;
extern const int _num__array_Core_0_kp;
extern double *_array_Core_0_lastspike;
extern const int _num__array_Core_0_lastspike;
extern char *_array_Core_0_not_refractory;
extern const int _num__array_Core_0_not_refractory;
extern double *_array_Core_0_soma_refP;
extern const int _num__array_Core_0_soma_refP;
extern double *_array_Core_0_std_pulse;
extern const int _num__array_Core_0_std_pulse;
extern double *_array_Core_0_tau_pulse;
extern const int _num__array_Core_0_tau_pulse;
extern double *_array_Core_0_Ut;
extern const int _num__array_Core_0_Ut;
extern double *_array_Core_0_Va;
extern const int _num__array_Core_0_Va;
extern double *_array_Core_0_Vw;
extern const int _num__array_Core_0_Vw;
extern int32_t *_array_Core_1__spikespace;
extern const int _num__array_Core_1__spikespace;
extern double *_array_Core_1_alpha_ahp;
extern const int _num__array_Core_1_alpha_ahp;
extern double *_array_Core_1_alpha_ampa;
extern const int _num__array_Core_1_alpha_ampa;
extern double *_array_Core_1_alpha_ampa_std;
extern const int _num__array_Core_1_alpha_ampa_std;
extern double *_array_Core_1_alpha_gaba_a;
extern const int _num__array_Core_1_alpha_gaba_a;
extern double *_array_Core_1_alpha_gaba_b;
extern const int _num__array_Core_1_alpha_gaba_b;
extern double *_array_Core_1_alpha_nmda;
extern const int _num__array_Core_1_alpha_nmda;
extern double *_array_Core_1_alpha_soma;
extern const int _num__array_Core_1_alpha_soma;
extern double *_array_Core_1_Campa;
extern const int _num__array_Core_1_Campa;
extern double *_array_Core_1_Campa_std;
extern const int _num__array_Core_1_Campa_std;
extern double *_array_Core_1_Cgaba_a;
extern const int _num__array_Core_1_Cgaba_a;
extern double *_array_Core_1_Cgaba_b;
extern const int _num__array_Core_1_Cgaba_b;
extern double *_array_Core_1_Cnmda;
extern const int _num__array_Core_1_Cnmda;
extern double *_array_Core_1_Csoma_ahp;
extern const int _num__array_Core_1_Csoma_ahp;
extern double *_array_Core_1_Csoma_mem;
extern const int _num__array_Core_1_Csoma_mem;
extern int32_t *_array_Core_1_i;
extern const int _num__array_Core_1_i;
extern double *_array_Core_1_I0;
extern const int _num__array_Core_1_I0;
extern double *_array_Core_1_Iampa;
extern const int _num__array_Core_1_Iampa;
extern double *_array_Core_1_Iampa_std;
extern const int _num__array_Core_1_Iampa_std;
extern double *_array_Core_1_Iampa_std_tau;
extern const int _num__array_Core_1_Iampa_std_tau;
extern double *_array_Core_1_Iampa_tau;
extern const int _num__array_Core_1_Iampa_tau;
extern double *_array_Core_1_Iampa_w0;
extern const int _num__array_Core_1_Iampa_w0;
extern double *_array_Core_1_Idischarge_w;
extern const int _num__array_Core_1_Idischarge_w;
extern double *_array_Core_1_Igaba_a;
extern const int _num__array_Core_1_Igaba_a;
extern double *_array_Core_1_Igaba_a_tau;
extern const int _num__array_Core_1_Igaba_a_tau;
extern double *_array_Core_1_Igaba_a_w0;
extern const int _num__array_Core_1_Igaba_a_w0;
extern double *_array_Core_1_Igaba_b;
extern const int _num__array_Core_1_Igaba_b;
extern double *_array_Core_1_Igaba_b_tau;
extern const int _num__array_Core_1_Igaba_b_tau;
extern double *_array_Core_1_Igaba_b_w0;
extern const int _num__array_Core_1_Igaba_b_w0;
extern double *_array_Core_1_Inmda;
extern const int _num__array_Core_1_Inmda;
extern double *_array_Core_1_Inmda_tau;
extern const int _num__array_Core_1_Inmda_tau;
extern double *_array_Core_1_Inmda_thr;
extern const int _num__array_Core_1_Inmda_thr;
extern double *_array_Core_1_Inmda_w0;
extern const int _num__array_Core_1_Inmda_w0;
extern double *_array_Core_1_Isoma_ahp;
extern const int _num__array_Core_1_Isoma_ahp;
extern double *_array_Core_1_Isoma_ahp_g;
extern const int _num__array_Core_1_Isoma_ahp_g;
extern double *_array_Core_1_Isoma_ahp_tau;
extern const int _num__array_Core_1_Isoma_ahp_tau;
extern double *_array_Core_1_Isoma_ahp_w;
extern const int _num__array_Core_1_Isoma_ahp_w;
extern double *_array_Core_1_Isoma_const;
extern const int _num__array_Core_1_Isoma_const;
extern double *_array_Core_1_Isoma_dpi_tau;
extern const int _num__array_Core_1_Isoma_dpi_tau;
extern double *_array_Core_1_Isoma_mem;
extern const int _num__array_Core_1_Isoma_mem;
extern double *_array_Core_1_Isoma_pfb_gain;
extern const int _num__array_Core_1_Isoma_pfb_gain;
extern double *_array_Core_1_Isoma_pfb_norm;
extern const int _num__array_Core_1_Isoma_pfb_norm;
extern double *_array_Core_1_Isoma_pfb_th;
extern const int _num__array_Core_1_Isoma_pfb_th;
extern double *_array_Core_1_Isoma_reset;
extern const int _num__array_Core_1_Isoma_reset;
extern double *_array_Core_1_Isoma_th;
extern const int _num__array_Core_1_Isoma_th;
extern double *_array_Core_1_kn;
extern const int _num__array_Core_1_kn;
extern double *_array_Core_1_kp;
extern const int _num__array_Core_1_kp;
extern double *_array_Core_1_lastspike;
extern const int _num__array_Core_1_lastspike;
extern char *_array_Core_1_not_refractory;
extern const int _num__array_Core_1_not_refractory;
extern double *_array_Core_1_soma_refP;
extern const int _num__array_Core_1_soma_refP;
extern double *_array_Core_1_std_pulse;
extern const int _num__array_Core_1_std_pulse;
extern int32_t *_array_Core_1_subgroup_2__sub_idx;
extern const int _num__array_Core_1_subgroup_2__sub_idx;
extern double *_array_Core_1_tau_pulse;
extern const int _num__array_Core_1_tau_pulse;
extern double *_array_Core_1_Ut;
extern const int _num__array_Core_1_Ut;
extern double *_array_Core_1_Va;
extern const int _num__array_Core_1_Va;
extern double *_array_Core_1_Vw;
extern const int _num__array_Core_1_Vw;
extern int32_t *_array_Core_2__spikespace;
extern const int _num__array_Core_2__spikespace;
extern double *_array_Core_2_alpha_ahp;
extern const int _num__array_Core_2_alpha_ahp;
extern double *_array_Core_2_alpha_ampa;
extern const int _num__array_Core_2_alpha_ampa;
extern double *_array_Core_2_alpha_ampa_std;
extern const int _num__array_Core_2_alpha_ampa_std;
extern double *_array_Core_2_alpha_gaba_a;
extern const int _num__array_Core_2_alpha_gaba_a;
extern double *_array_Core_2_alpha_gaba_b;
extern const int _num__array_Core_2_alpha_gaba_b;
extern double *_array_Core_2_alpha_nmda;
extern const int _num__array_Core_2_alpha_nmda;
extern double *_array_Core_2_alpha_soma;
extern const int _num__array_Core_2_alpha_soma;
extern double *_array_Core_2_Campa;
extern const int _num__array_Core_2_Campa;
extern double *_array_Core_2_Campa_std;
extern const int _num__array_Core_2_Campa_std;
extern double *_array_Core_2_Cgaba_a;
extern const int _num__array_Core_2_Cgaba_a;
extern double *_array_Core_2_Cgaba_b;
extern const int _num__array_Core_2_Cgaba_b;
extern double *_array_Core_2_Cnmda;
extern const int _num__array_Core_2_Cnmda;
extern double *_array_Core_2_Csoma_ahp;
extern const int _num__array_Core_2_Csoma_ahp;
extern double *_array_Core_2_Csoma_mem;
extern const int _num__array_Core_2_Csoma_mem;
extern int32_t *_array_Core_2_i;
extern const int _num__array_Core_2_i;
extern double *_array_Core_2_I0;
extern const int _num__array_Core_2_I0;
extern double *_array_Core_2_Iampa;
extern const int _num__array_Core_2_Iampa;
extern double *_array_Core_2_Iampa_std;
extern const int _num__array_Core_2_Iampa_std;
extern double *_array_Core_2_Iampa_std_tau;
extern const int _num__array_Core_2_Iampa_std_tau;
extern double *_array_Core_2_Iampa_tau;
extern const int _num__array_Core_2_Iampa_tau;
extern double *_array_Core_2_Iampa_w0;
extern const int _num__array_Core_2_Iampa_w0;
extern double *_array_Core_2_Idischarge_w;
extern const int _num__array_Core_2_Idischarge_w;
extern double *_array_Core_2_Igaba_a;
extern const int _num__array_Core_2_Igaba_a;
extern double *_array_Core_2_Igaba_a_tau;
extern const int _num__array_Core_2_Igaba_a_tau;
extern double *_array_Core_2_Igaba_a_w0;
extern const int _num__array_Core_2_Igaba_a_w0;
extern double *_array_Core_2_Igaba_b;
extern const int _num__array_Core_2_Igaba_b;
extern double *_array_Core_2_Igaba_b_tau;
extern const int _num__array_Core_2_Igaba_b_tau;
extern double *_array_Core_2_Igaba_b_w0;
extern const int _num__array_Core_2_Igaba_b_w0;
extern double *_array_Core_2_Inmda;
extern const int _num__array_Core_2_Inmda;
extern double *_array_Core_2_Inmda_tau;
extern const int _num__array_Core_2_Inmda_tau;
extern double *_array_Core_2_Inmda_thr;
extern const int _num__array_Core_2_Inmda_thr;
extern double *_array_Core_2_Inmda_w0;
extern const int _num__array_Core_2_Inmda_w0;
extern double *_array_Core_2_Isoma_ahp;
extern const int _num__array_Core_2_Isoma_ahp;
extern double *_array_Core_2_Isoma_ahp_g;
extern const int _num__array_Core_2_Isoma_ahp_g;
extern double *_array_Core_2_Isoma_ahp_tau;
extern const int _num__array_Core_2_Isoma_ahp_tau;
extern double *_array_Core_2_Isoma_ahp_w;
extern const int _num__array_Core_2_Isoma_ahp_w;
extern double *_array_Core_2_Isoma_const;
extern const int _num__array_Core_2_Isoma_const;
extern double *_array_Core_2_Isoma_dpi_tau;
extern const int _num__array_Core_2_Isoma_dpi_tau;
extern double *_array_Core_2_Isoma_mem;
extern const int _num__array_Core_2_Isoma_mem;
extern double *_array_Core_2_Isoma_pfb_gain;
extern const int _num__array_Core_2_Isoma_pfb_gain;
extern double *_array_Core_2_Isoma_pfb_norm;
extern const int _num__array_Core_2_Isoma_pfb_norm;
extern double *_array_Core_2_Isoma_pfb_th;
extern const int _num__array_Core_2_Isoma_pfb_th;
extern double *_array_Core_2_Isoma_reset;
extern const int _num__array_Core_2_Isoma_reset;
extern double *_array_Core_2_Isoma_th;
extern const int _num__array_Core_2_Isoma_th;
extern double *_array_Core_2_kn;
extern const int _num__array_Core_2_kn;
extern double *_array_Core_2_kp;
extern const int _num__array_Core_2_kp;
extern double *_array_Core_2_lastspike;
extern const int _num__array_Core_2_lastspike;
extern char *_array_Core_2_not_refractory;
extern const int _num__array_Core_2_not_refractory;
extern double *_array_Core_2_soma_refP;
extern const int _num__array_Core_2_soma_refP;
extern double *_array_Core_2_std_pulse;
extern const int _num__array_Core_2_std_pulse;
extern int32_t *_array_Core_2_subgroup_2__sub_idx;
extern const int _num__array_Core_2_subgroup_2__sub_idx;
extern double *_array_Core_2_tau_pulse;
extern const int _num__array_Core_2_tau_pulse;
extern double *_array_Core_2_Ut;
extern const int _num__array_Core_2_Ut;
extern double *_array_Core_2_Va;
extern const int _num__array_Core_2_Va;
extern double *_array_Core_2_Vw;
extern const int _num__array_Core_2_Vw;
extern int32_t *_array_Core_3__spikespace;
extern const int _num__array_Core_3__spikespace;
extern double *_array_Core_3_alpha_ahp;
extern const int _num__array_Core_3_alpha_ahp;
extern double *_array_Core_3_alpha_ampa;
extern const int _num__array_Core_3_alpha_ampa;
extern double *_array_Core_3_alpha_ampa_std;
extern const int _num__array_Core_3_alpha_ampa_std;
extern double *_array_Core_3_alpha_gaba_a;
extern const int _num__array_Core_3_alpha_gaba_a;
extern double *_array_Core_3_alpha_gaba_b;
extern const int _num__array_Core_3_alpha_gaba_b;
extern double *_array_Core_3_alpha_nmda;
extern const int _num__array_Core_3_alpha_nmda;
extern double *_array_Core_3_alpha_soma;
extern const int _num__array_Core_3_alpha_soma;
extern double *_array_Core_3_Campa;
extern const int _num__array_Core_3_Campa;
extern double *_array_Core_3_Campa_std;
extern const int _num__array_Core_3_Campa_std;
extern double *_array_Core_3_Cgaba_a;
extern const int _num__array_Core_3_Cgaba_a;
extern double *_array_Core_3_Cgaba_b;
extern const int _num__array_Core_3_Cgaba_b;
extern double *_array_Core_3_Cnmda;
extern const int _num__array_Core_3_Cnmda;
extern double *_array_Core_3_Csoma_ahp;
extern const int _num__array_Core_3_Csoma_ahp;
extern double *_array_Core_3_Csoma_mem;
extern const int _num__array_Core_3_Csoma_mem;
extern int32_t *_array_Core_3_i;
extern const int _num__array_Core_3_i;
extern double *_array_Core_3_I0;
extern const int _num__array_Core_3_I0;
extern double *_array_Core_3_Iampa;
extern const int _num__array_Core_3_Iampa;
extern double *_array_Core_3_Iampa_std;
extern const int _num__array_Core_3_Iampa_std;
extern double *_array_Core_3_Iampa_std_tau;
extern const int _num__array_Core_3_Iampa_std_tau;
extern double *_array_Core_3_Iampa_tau;
extern const int _num__array_Core_3_Iampa_tau;
extern double *_array_Core_3_Iampa_w0;
extern const int _num__array_Core_3_Iampa_w0;
extern double *_array_Core_3_Idischarge_w;
extern const int _num__array_Core_3_Idischarge_w;
extern double *_array_Core_3_Igaba_a;
extern const int _num__array_Core_3_Igaba_a;
extern double *_array_Core_3_Igaba_a_tau;
extern const int _num__array_Core_3_Igaba_a_tau;
extern double *_array_Core_3_Igaba_a_w0;
extern const int _num__array_Core_3_Igaba_a_w0;
extern double *_array_Core_3_Igaba_b;
extern const int _num__array_Core_3_Igaba_b;
extern double *_array_Core_3_Igaba_b_tau;
extern const int _num__array_Core_3_Igaba_b_tau;
extern double *_array_Core_3_Igaba_b_w0;
extern const int _num__array_Core_3_Igaba_b_w0;
extern double *_array_Core_3_Inmda;
extern const int _num__array_Core_3_Inmda;
extern double *_array_Core_3_Inmda_tau;
extern const int _num__array_Core_3_Inmda_tau;
extern double *_array_Core_3_Inmda_thr;
extern const int _num__array_Core_3_Inmda_thr;
extern double *_array_Core_3_Inmda_w0;
extern const int _num__array_Core_3_Inmda_w0;
extern double *_array_Core_3_Isoma_ahp;
extern const int _num__array_Core_3_Isoma_ahp;
extern double *_array_Core_3_Isoma_ahp_g;
extern const int _num__array_Core_3_Isoma_ahp_g;
extern double *_array_Core_3_Isoma_ahp_tau;
extern const int _num__array_Core_3_Isoma_ahp_tau;
extern double *_array_Core_3_Isoma_ahp_w;
extern const int _num__array_Core_3_Isoma_ahp_w;
extern double *_array_Core_3_Isoma_const;
extern const int _num__array_Core_3_Isoma_const;
extern double *_array_Core_3_Isoma_dpi_tau;
extern const int _num__array_Core_3_Isoma_dpi_tau;
extern double *_array_Core_3_Isoma_mem;
extern const int _num__array_Core_3_Isoma_mem;
extern double *_array_Core_3_Isoma_pfb_gain;
extern const int _num__array_Core_3_Isoma_pfb_gain;
extern double *_array_Core_3_Isoma_pfb_norm;
extern const int _num__array_Core_3_Isoma_pfb_norm;
extern double *_array_Core_3_Isoma_pfb_th;
extern const int _num__array_Core_3_Isoma_pfb_th;
extern double *_array_Core_3_Isoma_reset;
extern const int _num__array_Core_3_Isoma_reset;
extern double *_array_Core_3_Isoma_th;
extern const int _num__array_Core_3_Isoma_th;
extern double *_array_Core_3_kn;
extern const int _num__array_Core_3_kn;
extern double *_array_Core_3_kp;
extern const int _num__array_Core_3_kp;
extern double *_array_Core_3_lastspike;
extern const int _num__array_Core_3_lastspike;
extern char *_array_Core_3_not_refractory;
extern const int _num__array_Core_3_not_refractory;
extern double *_array_Core_3_soma_refP;
extern const int _num__array_Core_3_soma_refP;
extern double *_array_Core_3_std_pulse;
extern const int _num__array_Core_3_std_pulse;
extern int32_t *_array_Core_3_subgroup_2__sub_idx;
extern const int _num__array_Core_3_subgroup_2__sub_idx;
extern double *_array_Core_3_tau_pulse;
extern const int _num__array_Core_3_tau_pulse;
extern double *_array_Core_3_Ut;
extern const int _num__array_Core_3_Ut;
extern double *_array_Core_3_Va;
extern const int _num__array_Core_3_Va;
extern double *_array_Core_3_Vw;
extern const int _num__array_Core_3_Vw;
extern double *_array_defaultclock_dt;
extern const int _num__array_defaultclock_dt;
extern double *_array_defaultclock_t;
extern const int _num__array_defaultclock_t;
extern int64_t *_array_defaultclock_timestep;
extern const int _num__array_defaultclock_timestep;
extern int32_t *_array_GABA_B10_N;
extern const int _num__array_GABA_B10_N;
extern int32_t *_array_GABA_B4_N;
extern const int _num__array_GABA_B4_N;
extern int32_t *_array_GABA_B5_N;
extern const int _num__array_GABA_B5_N;
extern int32_t *_array_GABA_B6_N;
extern const int _num__array_GABA_B6_N;
extern int32_t *_array_GABA_B9_N;
extern const int _num__array_GABA_B9_N;
extern int32_t *_array_mon_neuron_input__source_idx;
extern const int _num__array_mon_neuron_input__source_idx;
extern int32_t *_array_mon_neuron_input_count;
extern const int _num__array_mon_neuron_input_count;
extern int32_t *_array_mon_neuron_input_N;
extern const int _num__array_mon_neuron_input_N;
extern int32_t *_array_PC_output__source_idx;
extern const int _num__array_PC_output__source_idx;
extern int32_t *_array_PC_output_count;
extern const int _num__array_PC_output_count;
extern int32_t *_array_PC_output_N;
extern const int _num__array_PC_output_N;
extern int32_t *_array_PV_output__source_idx;
extern const int _num__array_PV_output__source_idx;
extern int32_t *_array_PV_output_count;
extern const int _num__array_PV_output_count;
extern int32_t *_array_PV_output_N;
extern const int _num__array_PV_output_N;
extern int32_t *_array_SpikeGenerator__lastindex;
extern const int _num__array_SpikeGenerator__lastindex;
extern int32_t *_array_SpikeGenerator__period_bins;
extern const int _num__array_SpikeGenerator__period_bins;
extern int32_t *_array_SpikeGenerator__spikespace;
extern const int _num__array_SpikeGenerator__spikespace;
extern int32_t *_array_SpikeGenerator_i;
extern const int _num__array_SpikeGenerator_i;
extern double *_array_SpikeGenerator_period;
extern const int _num__array_SpikeGenerator_period;
extern int32_t *_array_SST_output__source_idx;
extern const int _num__array_SST_output__source_idx;
extern int32_t *_array_SST_output_count;
extern const int _num__array_SST_output_count;
extern int32_t *_array_SST_output_N;
extern const int _num__array_SST_output_N;
extern int32_t *_array_statemonitor_10__indices;
extern const int _num__array_statemonitor_10__indices;
extern double *_array_statemonitor_10_Iampa;
extern const int _num__array_statemonitor_10_Iampa;
extern int32_t *_array_statemonitor_10_N;
extern const int _num__array_statemonitor_10_N;
extern int32_t *_array_statemonitor_11__indices;
extern const int _num__array_statemonitor_11__indices;
extern double *_array_statemonitor_11_Iampa_std;
extern const int _num__array_statemonitor_11_Iampa_std;
extern int32_t *_array_statemonitor_11_N;
extern const int _num__array_statemonitor_11_N;
extern int32_t *_array_statemonitor_12__indices;
extern const int _num__array_statemonitor_12__indices;
extern double *_array_statemonitor_12_Igaba_b;
extern const int _num__array_statemonitor_12_Igaba_b;
extern int32_t *_array_statemonitor_12_N;
extern const int _num__array_statemonitor_12_N;
extern int32_t *_array_statemonitor_13__indices;
extern const int _num__array_statemonitor_13__indices;
extern double *_array_statemonitor_13_Igaba_b;
extern const int _num__array_statemonitor_13_Igaba_b;
extern int32_t *_array_statemonitor_13_N;
extern const int _num__array_statemonitor_13_N;
extern int32_t *_array_statemonitor_1__indices;
extern const int _num__array_statemonitor_1__indices;
extern double *_array_statemonitor_1_Isoma_mem;
extern const int _num__array_statemonitor_1_Isoma_mem;
extern int32_t *_array_statemonitor_1_N;
extern const int _num__array_statemonitor_1_N;
extern int32_t *_array_statemonitor_2__indices;
extern const int _num__array_statemonitor_2__indices;
extern double *_array_statemonitor_2_Isoma_mem;
extern const int _num__array_statemonitor_2_Isoma_mem;
extern int32_t *_array_statemonitor_2_N;
extern const int _num__array_statemonitor_2_N;
extern int32_t *_array_statemonitor_3__indices;
extern const int _num__array_statemonitor_3__indices;
extern double *_array_statemonitor_3_Iampa;
extern const int _num__array_statemonitor_3_Iampa;
extern int32_t *_array_statemonitor_3_N;
extern const int _num__array_statemonitor_3_N;
extern int32_t *_array_statemonitor_4__indices;
extern const int _num__array_statemonitor_4__indices;
extern double *_array_statemonitor_4_Iampa_std;
extern const int _num__array_statemonitor_4_Iampa_std;
extern int32_t *_array_statemonitor_4_N;
extern const int _num__array_statemonitor_4_N;
extern int32_t *_array_statemonitor_5__indices;
extern const int _num__array_statemonitor_5__indices;
extern double *_array_statemonitor_5_Iampa;
extern const int _num__array_statemonitor_5_Iampa;
extern int32_t *_array_statemonitor_5_N;
extern const int _num__array_statemonitor_5_N;
extern int32_t *_array_statemonitor_6__indices;
extern const int _num__array_statemonitor_6__indices;
extern double *_array_statemonitor_6_Iampa;
extern const int _num__array_statemonitor_6_Iampa;
extern int32_t *_array_statemonitor_6_N;
extern const int _num__array_statemonitor_6_N;
extern int32_t *_array_statemonitor_7__indices;
extern const int _num__array_statemonitor_7__indices;
extern double *_array_statemonitor_7_Igaba_b;
extern const int _num__array_statemonitor_7_Igaba_b;
extern int32_t *_array_statemonitor_7_N;
extern const int _num__array_statemonitor_7_N;
extern int32_t *_array_statemonitor_8__indices;
extern const int _num__array_statemonitor_8__indices;
extern double *_array_statemonitor_8_Igaba_b;
extern const int _num__array_statemonitor_8_Igaba_b;
extern int32_t *_array_statemonitor_8_N;
extern const int _num__array_statemonitor_8_N;
extern int32_t *_array_statemonitor_9__indices;
extern const int _num__array_statemonitor_9__indices;
extern double *_array_statemonitor_9_Igaba_b;
extern const int _num__array_statemonitor_9_Igaba_b;
extern int32_t *_array_statemonitor_9_N;
extern const int _num__array_statemonitor_9_N;
extern int32_t *_array_statemonitor__indices;
extern const int _num__array_statemonitor__indices;
extern double *_array_statemonitor_Isoma_mem;
extern const int _num__array_statemonitor_Isoma_mem;
extern int32_t *_array_statemonitor_N;
extern const int _num__array_statemonitor_N;

//////////////// dynamic arrays 2d /////////
extern DynamicArray2D<double> _dynamic_array_statemonitor_10_Iampa;
extern DynamicArray2D<double> _dynamic_array_statemonitor_11_Iampa_std;
extern DynamicArray2D<double> _dynamic_array_statemonitor_12_Igaba_b;
extern DynamicArray2D<double> _dynamic_array_statemonitor_13_Igaba_b;
extern DynamicArray2D<double> _dynamic_array_statemonitor_1_Isoma_mem;
extern DynamicArray2D<double> _dynamic_array_statemonitor_2_Isoma_mem;
extern DynamicArray2D<double> _dynamic_array_statemonitor_3_Iampa;
extern DynamicArray2D<double> _dynamic_array_statemonitor_4_Iampa_std;
extern DynamicArray2D<double> _dynamic_array_statemonitor_5_Iampa;
extern DynamicArray2D<double> _dynamic_array_statemonitor_6_Iampa;
extern DynamicArray2D<double> _dynamic_array_statemonitor_7_Igaba_b;
extern DynamicArray2D<double> _dynamic_array_statemonitor_8_Igaba_b;
extern DynamicArray2D<double> _dynamic_array_statemonitor_9_Igaba_b;
extern DynamicArray2D<double> _dynamic_array_statemonitor_Isoma_mem;

/////////////// static arrays /////////////
extern int32_t *_static_array__array_statemonitor_1__indices;
extern const int _num__static_array__array_statemonitor_1__indices;
extern int32_t *_static_array__array_statemonitor_2__indices;
extern const int _num__static_array__array_statemonitor_2__indices;
extern int32_t *_static_array__array_statemonitor__indices;
extern const int _num__static_array__array_statemonitor__indices;
extern int32_t *_static_array__dynamic_array_SpikeGenerator__timebins;
extern const int _num__static_array__dynamic_array_SpikeGenerator__timebins;
extern double *_static_array__dynamic_array_SpikeGenerator_neuron_index;
extern const int _num__static_array__dynamic_array_SpikeGenerator_neuron_index;
extern int64_t *_static_array__dynamic_array_SpikeGenerator_spike_number;
extern const int _num__static_array__dynamic_array_SpikeGenerator_spike_number;
extern double *_static_array__dynamic_array_SpikeGenerator_spike_time;
extern const int _num__static_array__dynamic_array_SpikeGenerator_spike_time;

//////////////// synapses /////////////////
// AMPA0
extern SynapticPathway AMPA0_post;
extern SynapticPathway AMPA0_pre;
// AMPA2
extern SynapticPathway AMPA2_post;
extern SynapticPathway AMPA2_pre;
// AMPA3
extern SynapticPathway AMPA3_post;
extern SynapticPathway AMPA3_pre;
// AMPA7
extern SynapticPathway AMPA7_post;
extern SynapticPathway AMPA7_pre;
// AMPA_STD1
extern SynapticPathway AMPA_STD1_post;
extern SynapticPathway AMPA_STD1_pre;
// AMPA_STD8
extern SynapticPathway AMPA_STD8_post;
extern SynapticPathway AMPA_STD8_pre;
// GABA_B10
extern SynapticPathway GABA_B10_post;
extern SynapticPathway GABA_B10_pre;
// GABA_B4
extern SynapticPathway GABA_B4_post;
extern SynapticPathway GABA_B4_pre;
// GABA_B5
extern SynapticPathway GABA_B5_post;
extern SynapticPathway GABA_B5_pre;
// GABA_B6
extern SynapticPathway GABA_B6_post;
extern SynapticPathway GABA_B6_pre;
// GABA_B9
extern SynapticPathway GABA_B9_post;
extern SynapticPathway GABA_B9_pre;

// Profiling information for each code object
}

void _init_arrays();
void _load_arrays();
void _write_arrays();
void _dealloc_arrays();

#endif


