#ifndef _INCLUDED_AMPA_STD8_synapses_create_generator_codeobject
#define _INCLUDED_AMPA_STD8_synapses_create_generator_codeobject

void _run_AMPA_STD8_synapses_create_generator_codeobject();


#endif
