#ifndef _INCLUDED_GABA_B5_synapses_create_generator_codeobject_1
#define _INCLUDED_GABA_B5_synapses_create_generator_codeobject_1

void _run_GABA_B5_synapses_create_generator_codeobject_1();


#endif
